# Generated by Django 3.2 on 2021-06-07 18:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, default='', max_length=200)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('y', 'Yayinda'), ('t', 'Taslak')], max_length=1)),
                ('page_type', models.CharField(choices=[('u', 'Üst menü'), ('y', 'Yan Menü'), ('a', 'Alt Menü')], max_length=1)),
                ('order', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toursite.page')),
            ],
        ),
    ]
