# Generated by Django 3.2 on 2021-06-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toursite', '0002_tour_tourcategory_tourphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_dollar', models.FloatField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toursite.tour')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toursite.tourcategory')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toursite.tour')),
            ],
        ),
    ]
