# Generated by Django 3.2 on 2021-06-07 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toursite', '0003_categorytour_tourprices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourprices',
            old_name='price_dollar',
            new_name='price_dollar_for_double',
        ),
        migrations.AddField(
            model_name='tourprices',
            name='price_dollar_for_single',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourprices',
            name='price_dollar_for_with_child',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourprices',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
